pipeline {
    agent any

    environment {
        NODEJS_HOME = tool name: 'NodeJS 14.18.1' // Name of the NodeJS tool you configured
        PATH = "${NODEJS_HOME}/bin:${env.PATH}"
        DOCKER_IMAGE = 'myregistry/my-nodejs-react-app:latest' // Replace with your Docker registry URL
        DOCKER_CREDENTIALS = 'Docker-hub-credentials' // Docker Hub/Registry credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test' // Ensure you have test scripts in package.json
            }
        }

        stage('Build React App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS) {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }
    }

    post {
        success {
            mail to: 'arangarajan16.002@gmail.com',
                 subject: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: "Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' succeeded. Check the results at ${env.BUILD_URL}."
        }
        failure {
            mail to: 'arangarajan16.002@gmail.com',
                 subject: "FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: "Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' failed. Check the results at ${env.BUILD_URL}."
        }
    }
}
