pipeline {
    agent {
        docker {
            image 'node:14'   // Use Node.js version 14 for the Docker image
            label 'docker'     // Ensure the agent has the 'docker' label
        }
    }

    environment {
        // Docker registry variables
        DOCKER_REGISTRY = 'aero1602'  // Replace with your Docker registry
        DOCKER_IMAGE = 'reactimage-jenkins'          // Replace with your Docker image name
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials' // Your Docker Hub credentials ID in Jenkins
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Clone the repository from GitHub
                git 'https://github.com/jenkins-docs/simple-node-js-react-npm-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Install Node.js dependencies using npm
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                // Run tests using npm
                sh 'npm test'
            }
        }

        stage('Build React App') {
            steps {
                // Build the React application
                sh 'npm run build'
            }
        }

        stage('Package App in Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    docker.build("${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Push Docker Image to Registry') {
            steps {
                script {
                    // Push Docker image to the registry
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        docker.image("${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }
    }

    post {
        success {
            // Send an email notification on successful pipeline completion
            mail to: 'arangarajan16.002@gmail.com',
                 subject: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: "Build succeeded! Job: ${env.JOB_NAME} [${env.BUILD_NUMBER}] \n Check it here: ${env.BUILD_URL}"
        }

        failure {
            // Send an email notification if the pipeline fails
            mail to: 'arangarajan16.002@gmail.com',
                 subject: "FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: "Build failed! Job: ${env.JOB_NAME} [${env.BUILD_NUMBER}] \n Check it here: ${env.BUILD_URL}"
        }
    }
}
