pipeline {
    agent any
    
    environment {
        DOCKER_REGISTRY = 'aero1602' // Your Docker registry name
        DOCKER_IMAGE = 'simple-node-js-react-npm-app' // Your Docker image name
        EMAIL_RECIPIENT = 'arangarajan16.002@gmail.com' // Your email
    }

     stages {
        stage('Clean Workspace') {
            steps {
                sh 'rm -rf node_modules'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

      stage('Build Docker Image') {
    steps {
        script {
            def appVersion = "${env.BUILD_ID}"
            sh "docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${appVersion} -f jenkins/Dockerfile ."
            echo "Docker image built successfully"
            sh 'docker images'
        }
    }
}

        
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry([credentialsId: 'Docker-hub-credentials', url: 'https://index.docker.io/v1/']) {
                        sh "docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${env.BUILD_ID}"
                        echo "Docker image pushed successfully"
                    }
                }
            }
        }
    }

    post {
        success {
            mail to: "${EMAIL_RECIPIENT}",
                 subject: "Build Successful: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "The build was successful! You can see the build details here: ${env.BUILD_URL}"
        }
        failure {
            mail to: "${EMAIL_RECIPIENT}",
                 subject: "Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "The build failed. Please check the details here: ${env.BUILD_URL}"
        }
    }
}
